baseURL = 'https://www.createdirectusapp.com'
languageCode = 'en'
title = 'Directus Developer Guide'
theme = "hugo-theme-learn"

[params]
editUrl = "https://github.com/ChappIO/www.createdirectusapp.com/blob/main/content/"
author = "Thomas Biesaart"

[outputs]
home = ["HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github Repo"
identifier = "github"
url = "https://github.com/ChappIO/www.createdirectusapp.com"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-book'></i> Directus Docs"
identifier = "directus"
url = "https://docs.directus.io/extensions/introduction.html"
weight = 15
