baseURL = 'http://localhost:1313'
languageCode = 'en'
title = 'My New Hugo Site'
theme = "hugo-theme-learn"

[params]
editUrl = "https://github.com/ChappIO/directus-extension-development-guide/blob/main/content/"

[outputs]
home = ["HTML", "RSS", "JSON"]
